#!/bin/sh
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config window_placement second_child
yabai -m config window_topmost on
yabai -m config window_shadow on
yabai -m config window_opacity off
yabai -m config auto_balance off
yabai -m config split_ratio 0.5

# general space settings
gap=10
yabai -m config layout bsp
yabai -m config top_padding 5
yabai -m config bottom_padding 5
yabai -m config left_padding 5
yabai -m config right_padding 5
yabai -m config window_gap 20

# mouse settings
yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse off
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m mouse_drop_action swap

# window rules
yabai -m rule --add app="^(Docker|System Settings|Finder|Bitwarden|zoom.us)" manage=off

# external bar (to play nice with spacebar)
yabai -m config external_bar all:26:0

echo "yabai configuration loaded..."
